"""Agregar campo mesa_asignada_at para cronometro preciso

Revision ID: 4f9b2e7a3466
Revises: 
Create Date: 2025-08-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4f9b2e7a3466'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('cantidad_comensales', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_table', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('atendido_at', sa.DateTime(), nullable=True),
    sa.Column('mesa_asignada_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('ocupada', sa.Boolean(), nullable=True),
    sa.Column('llego_comensal', sa.Boolean(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('reservada', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajador')
    op.drop_table('mesa')
    op.drop_table('cliente')
    # ### end Alembic commands ###
