"""se agrego el campo reservada a Mesa

Revision ID: 6d8307b9ed38
Revises: fe55a8942716
Create Date: 2025-07-31 18:24:08.586412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8307b9ed38'
down_revision = 'fe55a8942716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.drop_column('reservada')

    # ### end Alembic commands ###
