"""se agrego capacidad a las mesas

Revision ID: 9109061a9879
Revises: 6d8307b9ed38
Create Date: 2025-08-08 16:56:10.366259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9109061a9879'
down_revision = '6d8307b9ed38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###
