"""se agrego el campo orden a mesa

Revision ID: bb1c6da7fee9
Revises: 9109061a9879
Create Date: 2025-08-09 02:23:36.462729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1c6da7fee9'
down_revision = '9109061a9879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
