"""agregar nombre y comnesales al modelo de cliente

Revision ID: f30e326fc11d
Revises: f3c96f19235a
Create Date: 2025-07-30 17:01:23.010905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30e326fc11d'
down_revision = 'f3c96f19235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cantidad_comensales', sa.Integer(), nullable=True))

    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trabajador_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_trabajador_username'), ['username'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('cantidad_comensales')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
