"""cambiar_nombre_por_email

Revision ID: f3c96f19235a
Revises: 
Create Date: 2025-07-28 18:52:32.021405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c96f19235a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_trabajador_email', ['email'])
        batch_op.create_unique_constraint('uq_trabajador_username', ['username'])
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('uq_trabajador_username', type_='unique')
        batch_op.drop_constraint('uq_trabajador_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
